runmode: debug # debug, release, test
addr: :60001
name: apiserver
url: http://127.0.0.1:60001
max_ping_count: 10
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
